---
Documentation:
    Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 130
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
