# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.5.1'

gem 'celluloid-io', '~> 0.17'
gem 'foreman', '~> 0.85'
gem 'haml', '~> 5.0', '>= 5.0.4'
gem 'httparty', '~> 0.16'
gem 'pg', '~> 1.1'
gem 'puma', '~> 3.12'
gem 'rumoji', '>= 0.5'
gem 'sequel', '~> 5.14'
gem 'sinatra', '~> 2.0', '>= 2.0.3'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.3'
gem 'sinatra-flash', '~> 0.3.0'
gem 'slack-ruby-bot', '~> 0.11.1'
gem 'stackdriver', '~> 0.15'

group :development, :test do
  gem 'dotenv', '~> 2.5'
  gem 'rake', '~> 12.3'
end

group :test do
  gem 'rack-test', '~> 1.1'
  gem 'rubocop', '~> 0.60'
  gem 'rubocop-rspec', '~> 1.30'
  gem 'vcr', '~> 4.0'
  gem 'webmock', '~> 3.4'
end
